version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "newhoggy"
    assignees:
      - "newhoggy"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "newhoggy"
    assignees:
      - "newhoggy"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"