# cargo-deny configuration file
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
]

[advisories]
version = 2
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore
ignore = [
    # paste crate is unmaintained but used by nushell dependencies
    # This is a transitive dependency we can't easily control
    "RUSTSEC-2024-0436",  # paste crate no longer maintained
    
    # TODO: Remove this ignore when upgrading to newer Nushell versions
    # proc-macro-error is unmaintained but used by nu-derive-value in Nushell 0.95.0
    # This should be resolved in newer Nushell versions that don't use this crate
    "RUSTSEC-2024-0370",  # proc-macro-error unmaintained
]

[licenses]
version = 2
# The confidence threshold for detecting a license from a license text
confidence-threshold = 0.8
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception", 
    "BSD-2-Clause",
    "BSD-3-Clause",
    "0BSD",
    "ISC",
    # TODO: Review and remove unused license allowances when upgrading dependencies
    # The following licenses are currently not used but kept for future compatibility
    # "Unicode-DFS-2016",  # Not currently used
    # "CC0-1.0",          # Not currently used  
    # "MPL-2.0",          # Not currently used
    "Unicode-3.0",
    "CC-PDDC",
    "Zlib",
]
# List of explicitly disallowed licenses
exceptions = [
    # Allow copyleft licenses for specific crates if needed
]

[bans]
# Lint level for when multiple versions of the same crate are detected
# TODO: Change back to "warn" when Nushell ecosystem has fewer duplicate dependencies
# Currently set to "allow" due to many transitive dependency version conflicts in Nushell 0.95.0
multiple-versions = "allow"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"
# The graph highlighting used when creating dotgraphs for crates
highlight = "all"
# List of crates that are allowed
allow = []
# List of crates to deny
deny = [
    # Deny crates with known security issues
    { name = "openssl", version = "*" },
]
# Certain crates/versions that will be skipped when doing duplicate detection
skip = []
# Similarly to `skip` allows you to skip certain crates from being checked
skip-tree = []

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"
# List of URLs for allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []