name: Documentation Improvement
description: Suggest improvements to documentation, guides, or examples
title: "[Docs]: "
labels: ["documentation", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Your suggestions help make nu_plugin_nw_ulid more accessible to everyone.

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - User Guide
        - API Reference
        - Developer Guide
        - Performance Guide
        - Migration Guide
        - Script Templates
        - README
        - Code Comments
        - Examples
        - Tutorials
    validations:
      required: true

  - type: textarea
    id: current_issue
    attributes:
      label: Current Issue
      description: What's unclear, missing, or incorrect in the current documentation?
      placeholder: Describe what's problematic with the current documentation...
    validations:
      required: true

  - type: textarea
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: Describe your suggested improvements...
    validations:
      required: true

  - type: textarea
    id: target_audience
    attributes:
      label: Target Audience
      description: Who would benefit from this improvement?
      placeholder: |
        - New users
        - Experienced developers
        - System administrators
        - DevOps engineers
        - etc.

  - type: textarea
    id: specific_sections
    attributes:
      label: Specific Sections
      description: If applicable, specify which sections, files, or pages need improvement
      placeholder: |
        - File: docs/USER_GUIDE.md, Section: "Quick Start"
        - Template: templates/api-request-tracking.nu
        - Function: `ulid generate` documentation

  - type: textarea
    id: examples_needed
    attributes:
      label: Examples Needed
      description: What kind of examples would be helpful?
      placeholder: |
        - Code examples
        - Real-world use cases
        - Step-by-step tutorials
        - Video demonstrations

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this improvement?
      options:
        - Low - Nice to have
        - Medium - Would help users
        - High - Blocks user understanding
        - Critical - Documentation is incorrect/misleading
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help with this improvement?
      options:
        - label: I can help write the documentation
        - label: I can provide examples or use cases
        - label: I can review the improved documentation
        - label: I can test the examples

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar documentation requests
          required: true
        - label: I have checked the current documentation thoroughly
          required: true
        - label: This improvement would benefit other users, not just my specific use case
          required: true