name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.1.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ inputs.version }}
      tag_name: v${{ inputs.version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate version format
      run: |
        if [[ ! "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. Expected: x.y.z"
          exit 1
        fi

    - name: Create and push tag
      run: |
        TAG_NAME="v${{ inputs.version }}"
        echo "Creating tag: $TAG_NAME"
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete existing release if it exists
      run: |
        TAG_NAME="v${{ inputs.version }}"
        echo "Checking for existing release..."
        if gh release view $TAG_NAME >/dev/null 2>&1; then
          echo "Release $TAG_NAME exists, deleting..."
          gh release delete $TAG_NAME --yes
          echo "Release deleted successfully"
        else
          echo "No existing release found"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ inputs.version }}
        name: Release v${{ inputs.version }}
        draft: false
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        fail_on_unmatched_files: false
        body: |
          ## What's Changed
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ### Via Cargo
          ```bash
          cargo install nw-nu_plugin_ulid
          ```
          
          ### Via Binary
          Download the appropriate binary for your platform from the assets below.
          
          ## Usage
          
          After installation, register the plugin with Nushell:
          ```bash
          plugin add ./nu_plugin_ulid
          plugin use ulid
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    name: Build and Upload
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: nu_plugin_ulid
            asset_name: nu_plugin_ulid-v${{ needs.create-release.outputs.version }}-linux-x86_64.tar.gz
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: nu_plugin_ulid
            asset_name: nu_plugin_ulid-v${{ needs.create-release.outputs.version }}-linux-aarch64.tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: nu_plugin_ulid.exe
            asset_name: nu_plugin_ulid-v${{ needs.create-release.outputs.version }}-windows-x86_64.zip
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: nu_plugin_ulid
            asset_name: nu_plugin_ulid-v${{ needs.create-release.outputs.version }}-macos-x86_64.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: nu_plugin_ulid
            asset_name: nu_plugin_ulid-v${{ needs.create-release.outputs.version }}-macos-aarch64.tar.gz

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-release-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release binary
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      run: cargo build --release --target ${{ matrix.target }}

    - name: Create archive (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        tar -czf ../../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}

    - name: Create archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}

  upload-assets:
    name: Upload Release Assets
    needs: [create-release, build-and-upload]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Upload assets to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.create-release.outputs.tag_name }}
        files: |
          **/*.tar.gz
          **/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-crate:
    name: Publish to Crates.io
    needs: [create-release, upload-assets]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ubuntu-latest-cargo-publish-${{ hashFiles('**/Cargo.lock') }}

    - name: Run quality gates before publishing
      run: |
        echo "🔍 Running Quality Gates..."
        
        # Code quality
        echo "📋 Checking code quality..."
        cargo clippy --all-targets --all-features -- -D warnings
        cargo fmt --all --check
        
        # Testing
        echo "🧪 Running tests..."
        cargo test --all-features --release
        
        # Security
        echo "🔒 Security audit..."
        cargo install cargo-audit --locked
        cargo audit
        
        echo "✅ All quality gates passed!"

    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
      run: |
        echo "📦 Publishing to crates.io..."
        cargo publish --token "$CARGO_REGISTRY_TOKEN"
        echo "✅ Successfully published to crates.io!"